export const NODE_NAMES: Record<string, string> = {
    Executable: '실행 가능한 노드',
    Evaluable: '값이 있는 노드',
    Keyword: '키워드',
    Operator: '연산자',
    Expression: '식',
    Block: '코드 덩어리',
    ValueGroup: '괄호로 묶인 값',
    Formula: '계산식',
    DeclareFunction: '약속',
    FunctionInvoke: '약속 실행',
    IfStatement: '조건문',
    IndexedValue: '인덱스가 있는 값',
    Sequence: '순서가 있는 값',
    List: '목록',
    Indexing: '인덱스',
    IndexFetch: '인덱스로 값 가져오기',
    SetToIndex: '인덱스에 값 저장하기',
    RangeOperator: '범위 만들기',
    ListLoop: '목록 반복문',
    Break: '반복 그만',
    EOL: '다음 줄',
    Indent: '들여쓰기',
    Print: '보여주기',
    PlusOperator: '더하기',
    MinusOperator: '빼기',
    MultiplyOperator: '곱하기',
    DivideOperator: '나누기',
    EqualOperator: '같다',
    AndOperator: '그리고',
    GreaterThanOperator: '크다',
    LessThanOperator: '작다',
    GreaterThanOrEqualOperator: '크거나 같다',
    LessThanOrEqualOperator: '작거나 같다',
    PrimitiveValue: '값',
    NumberValue: '숫자',
    StringValue: '문자',
    BooleanValue: '참거짓',
    Return: '약속 그만',
    Variable: '변수',
    SetVariable: '변수에 값 저장하기',
}
